name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: python -m pytest

     - name: Install gdown
       run: pip install gdown

     - name: Download ChromaDB contents
       run: |
         mkdir -p chromadb_contents
         gdown --folder "${{ secrets.CHROMADB_CONTENTS }}" -O chromadb_contents

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lrdisco2rag:latest

    - name: Save Docker image
      run: docker save lrdisco2rag:latest -o lrdisco2rag.tar

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: lrdisco2rag.tar
